version: '3.7'

services:
  mywordpress:
    image: wordpress:5.7
    restart: always
    ports:
      - 9012:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_password
      WORDPRESS_DB_NAME: Wordpress
    depends_on: 
      db: 
         condition: service_healthy
    volumes:
      - wordpress-volume:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Wordpress
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - db-vol:/var/lib/mysql
      
volumes:
  wordpress-volume:
  db-vol:
